const GeorgesFrench = new Map([
[1, ["paisible", "calm"]],
[2, ["Une chorale", "choir"]],
[3, ["Les légumes", "vegetables"]],
[4, ["Bulgarie", "Bulgaria"]],
[5, ["norvége", "Norway"]],
[6, ["suede", "Sweden"]],
[7, ["scandinavie", "Scandinavia"]],
[8, ["Abîmé cassé", "ruined, broken"]],
[9, ["L’appareil", "device or apparatus"]],
[10, ["la machine", "device"]],
[11, ["Carton", "box"]],
[12, ["boîte", "box"]],
[13, ["Content", "content"]],
[14, ["heureux", "happy"]],
[15, ["satisfait", "satisfied"]],
[16, ["satisfaire", "to satisfy"]],
[17, ["Décrire", "Describe"]],
[18, ["expliquer", "Explain"]],
[19, ["donner des details", "Give details"]],
[20, ["Expédier", "Dispatch"]],
[21, ["envoyer", "Send"]],
[22, ["Fonctionner", "function"]],
[23, ["marcher", "work"]],
[24, ["L’ingénieur", "engineers (“avec un diplôme”)"]],
[25, ["Nécessaire", "Necessary"]],
[26, ["indispensable", "Indespensible"]],
[27, ["obligatoire", "Obligatory"]],
[28, ["Surpris", "Surprise"]],
[29, ["étonné", "Surprised"]],
[30, ["Une équipe", "a groupe"]],
[31, ["Sans + infinitive", "without (verb form)"]],
[32, ["Eux", "them"]],
[33, ["Problème", "Problem"]],
[34, ["L’efficacité", "productivity"]],
[35, ["Mécontent", "malcontent"]],
[36, ["insatisfait", "dissatisfied"]],
[37, ["Navré", "Ashamed"]],
[38, ["pronfondément desolé", "Profoundly sorry"]],
[39, ["Prolonger", "prolong"]],
[40, ["Accorder du temps", "prolong"]],
[41, ["Résoudre", "Resolve"]],
[42, ["Régler (Résoudre)", "Settle"]],
[43, ["Responsabilité", "Responsibility"]],
[44, ["Le devoir (responsabilité)", "Obligation"]],
[45, ["On les a réparés", "we repaired them"]],
[46, ["On les lui a rendus", "we returned them to him"]],
[47, ["On te les a envoyés", "we sent them to you"]],
[48, ["L’accueil, l’endroit", "reception"]],
[49, ["Disponible", "available"]],
[50, ["libre", "free"]],
[51, ["Occupé", "Occupied"]],
[52, ["pris", "Taken (Occupied)"]],
[53, ["Regretter", "Regret"]],
[54, ["être contrarié", "To be frustrated"]],
[55, ["Le remplaçant, la remplaçante", "temp and replacement"]],
[56, ["Transmettre", "relay"]],
[57, ["Rappeler", "revert and call"]],
[58, ["Consulter", "consult (a calendar)"]],
[59, ["Les renseignements", "information comme « Auskunft »"]],
[60, ["Ravi", "thrilled"]],
[61, ["enthousiaste", "enthusiastic"]],
[62, ["Souhaiter", "to wish"]],
[63, ["Se sembler", "seem and appear"]],
[64, ["Le concurrent", "Competitor"]],
[65, ["le rival", "Rival"]],
[66, ["Les coordonnées", "contact details"]],
[67, ["Emplacement", "place"]],
[68, ["le lieu", "place"]],
[69, ["l’endroit", "place"]],
[70, ["Se désister", "step aside"]],
[71, ["se retirer", "pull back"]],
[72, ["annuler", "cancel (participation)"]],
[73, ["L’exposant", "exhibitor"]],
[74, ["Se démarquer", "distinguish"]],
[75, ["Attirer", "attract - rouse (incentivise)"]],
[76, ["tenter", "tempt"]],
[77, ["inciter", "incite"]],
[78, ["Animé", "animated"]],
[79, ["vivant", "lively"]],
[80, ["dynamique", "dynamic"]],
[81, ["Potentiel", "potential"]],
[82, ["éventuel", "potential"]],
[83, ["possible", "possible"]],
[84, ["Chaleureux", "welcoming"]],
[85, ["accueillant", "receptive"]],
[86, ["Su", "knew"]],
[87, ["Garder", "keep"]],
[88, ["L’horaire", "timetable"]],
[89, ["L’itinéraire", "itinerary"]],
[90, ["le parcours", "process"]],
[91, ["Effectuer", "implement"]],
[92, ["réaliser", "realise"]],
[93, ["accomplir", "carry out"]],
[94, ["L’escale", "stop-off"]],
[95, ["Le déplacement (professionnel)", "business trip"]],
[96, ["Le reçu", "receipt (large sum)"]],
[97, ["l’addition", "bill"]],
[98, ["Inclure", "contenir - to include (items and costs)"]],
[99, ["Modifier", "modify"]],
[100, ["changer", "change"]],
[101, ["varier", "vary"]],
[102, ["Eloigné", "distanced"]],
[103, ["retiré", "distant"]],
[104, ["Bruyant", "noisy"]],
[105, ["Une longue file", "a long line"]],
[106, ["Laine", "wool"]],
[107, ["Amener", "to bring"]],
[108, ["Eteindre", "turn off"]],
[109, ["Montrer", "to show"]],
[110, ["Montre", "watch"]],
[111, ["Prévenir", "prevent"]],
[112, ["Dès que", "as soon as"]],
[113, ["Planifier", "plan"]],
[114, ["prévoir", "forecast"]],
[115, ["Avoir Hâte De", "I can’t wait for"]],
[116, ["Alentours environs", "surroundings"]],
[117, ["Loin", "far"]],
[118, ["Insister", "insist"]],
[119, ["dire avec fermeté", "say with firmness"]],
[120, ["Se divertir", "enjoy oneself"]],
[121, ["s’amuser", "have fun"]],
[122, ["Se détendre", "relax"]],
[123, ["se reposer", "relax"]],
[124, ["Le séjour", "sojourn"]],
[125, ["Passionant", "passionate"]],
[126, ["captivant", "captivating"]],
[127, ["Aimable", "amiable"]],
[128, ["poli", "polite"]],
[129, ["bienveillant", "kindly"]],
[130, ["Me conduire", "drive me"]],
[131, ["Avoir encore", "still have"]],
[132, ["Voisine", "neighbouring"]],
[133, ["Assister au", "assist with"]],
[134, ["Auquels", "To whom"]],
[135, ["Accueillir", "To receive"]],
[136, ["Accorder", "Give"]],
[137, ["Constater", "note"]],
[138, ["se rendre compte", "become aware"]],
[139, ["La dette", "debt"]],
[140, ["La facture", "invoice"]],
[141, ["Faire parvenir à", "forward"]],
[142, ["transférer", "(transactional and transfer and informational) send"]],
[143, ["La gestion", "management"]],
[144, ["Le suivi", "Follow-up"]],
[145, ["Le paiement", "payment"]],
[146, ["le règlement", "settlement"]],
[147, ["Partiel", "partial"]],
[148, ["incomplet", "incomplete"]],
[149, ["Prochain", "next"]],
[150, ["suivant", "next"]],
[151, ["dans l’avenir", "In the future"]],
[152, ["Reporter", "postpone"]],
[153, ["renvoyer à plus tard", "postpone"]],
[154, ["Un prêt", "a loan"]],
[155, ["Les employées étaient ainsi devenues des amies", "Thus the employees became friends"]],
[156, ["Entretien d’embauche", "job interview"]],
[157, ["Stagiaire", "intern"]],
[158, ["Puisque", "since"]],
[159, ["Depuis que", "ever since"]],
[160, ["Tel que", "such as"]],
[161, ["S’attendre à", "expect"]],
[162, ["Se charger de", "take care of sth"]],
[163, ["s’occuper de", "see to sth"]],
[164, ["La commande", "order"]],
[165, ["l’achat", "purchase"]],
[166, ["Le comptable", "accountant"]],
[167, ["Confirmer", "confirm"]],
[168, ["assurer", "confirm"]],
[169, ["affirmer", "confirm"]],
[170, ["Étonnant", "surprising"]],
[171, ["surprenant", "astounding"]],
[172, ["Fiable", "serious (reliable)"]],
[173, ["sérieux", "serious"]],
[174, ["L’inventaire", "le catalogue"]],
[175, ["Retarder", "postpone"]],
[176, ["renvoyer", "postpone"]],
[177, ["La société", "company"]],
[178, ["l’entreprise", "enterprise"]],
[179, ["Ce que", "what (question)"]],
[180, ["La veille", "day before"]],
[181, ["La boutique", "salon"]],
[182, ["magasin", "shop"]],
[183, ["Le centre commercial", "commercial district"]],
[184, ["Le cirage", "polish"]],
[185, ["cirager", "to polish"]],
[186, ["ciragé", "polished"]],
[187, ["Dépenser", "spend"]],
[188, ["Essayer (vêtement)", "try on"]],
[189, ["Ainsi", "thus"]],
[190, ["Autrefois", "formerly"]],
[191, ["D’abord", "once"]],
[192, ["Avaler", "to swallow"]],
[193, ["Fauve", "fawn"]],
[194, ["Vierge", "virgin"]],
[195, ["La proie", "prey"]],
[196, ["Entièr(été)", "whole (old/(belgian))"]],
[197, ["Mâcher", "chew"]],
[198, ["Bouger", "to move (animals snakes insects objects cars lamps), to shift"]],
[199, ["Réfléchir", "to reflect"]],
[200, ["J’ai réussi", "I succeeded"]],
[201, ["Tracer", "trace"]],
[202, ["Chef-d’oeuvre", "masterpiece"]],
[203, ["Chapeau", "hat"]],
[204, ["Intéresser à", "interest in"]],
[205, ["L’insuccès", "unsuccess"]],
[206, ["Métier", "occupation"]],
[207, ["Utile", "useful"]],
[208, ["Dessins", "drawings"]],
[209, ["Plutôt", "instead"]],
[210, ["Peinture", "painting"]],
[211, ["Voler", "fly"]],
[212, ["Partout", "everywhere"]],
[213, ["Coup d’oeil", "glance"]],
[214, ["Egarer", "lost (geographically)"]],
[215, ["Des tas de…", "lots of"]],
[216, ["Tas", "heap"]],
[217, ["Vécu", "lived"]],
[218, ["Amélioré", "improved"]],
[219, ["Amélioration", "improvement"]],
[220, ["Paraître", "to appear"]],
[221, ["Étoiles", "stars"]],
[222, ["Véritablement", "truly, really"]],
[223, ["A Peine", "hardly"]],
[224, ["Sable", "sand"]],
[225, ["Naufragé", "shipwrecked mariner"]],
[226, ["Radeau", "raft"]],
[227, ["Mille", "thousand and mile"]],
[228, ["Hein!", "what"]],
[229, ["Sauter", "jump"]],
[230, ["Frotter", "rub"]],
[231, ["Frapper", "strike"]],
[232, ["Foudre", "lightning"]],
[233, ["Tout à fait", "completely"]],
[234, ["exactement", "exactly"]],
[235, ["Faute", "mistake"]],
[236, ["L’étonnement", "astonishment"]],
[237, ["Or", "but"]],
[238, ["Doucement", "gently"]],
[239, ["Impressionnant", "impressive"]],
[240, ["Oser faire", "dare to do sumth"]],
[241, ["Désobéir", "disobey"]],
[242, ["Poche", "pocket"]],
[243, ["Feuille", "leaf"]],
[244, ["Stylographe", "pen"]],
[245, ["Surtout", "above all"]],
[246, ["Encombrant", "bulky"]],
[247, ["Bélier", "ram"]],
[248, ["Corne", "horn"]],
[249, ["Vieux", "old"]],
[250, ["Griffonner", "sketch"]],
[251, ["Dedans", "inside"]],
[252, ["Pencher", "tilt"]],
[253, ["Se failler", "To crack"]],
[254, ["Endormir", "to fall asleep"]],
[255, ["Tiens !", "Damn!"]],
[256, ["Il me fallut", "I had to"]],
[257, ["Par hasard", "By chance"]],
[258, ["Peu à peu", "bit by bit and little by little"]],
[259, ["Entendre", "hear"]],
[260, ["Aperçu", "surveyed"]],
[261, ["Fier", "proud"]],
[262, ["Ecrier", "shout and cry"]],
[263, ["Éclat de rire", "burst of laughter"]],
[264, ["Hocher", "nod"]],
[265, ["Là-dessus", "With that"]],
[266, ["S’enfoncer", "sink"]],
[267, ["S’efforcer", "strive and endeavour"]],
[268, ["Drôle", "funny"]],
[269, ["Ajouter", "add"]],
[270, ["Droit devant soi on ne peut pas aller bien loin", "straight ahead of oneself won’t get you far"]],
[271, ["Vieillir", "to grow old"]],
[272, ["Chiffre", "figure"]],
[273, ["Refaire", "redo"]],
[274, ["Agir", "act"]],
[275, ["Il s’agit de", "be about"]],
[276, ["Épines", "thorns"]],
[277, ["La voix", "voice"]],
[278, ["S’etirer", "stretch"]],
[279, ["Ravissant", "delightful"]],
[280, ["charmant", "delightful"]],
[281, ["Radis", "radish"]],
[282, ["Une brindle", "twig"]],
[283, ["Arracher (plant)", "pull out"]],
[284, ["Or", "yet"]],
[285, ["Soigneusement", "carefully"]],
[286, ["S’astreindre", "commit oneself"]],
[287, ["Se frôler", "skim past each other"]],
[288, ["Douceur", "softness"]],
[289, ["Laid", "ugly"]],
[290, ["Secouer", "shake"]],
[291, ["Cramoisi", "crimson"]],
[292, ["Gonfler", "swell"]],
[293, ["Orgueil", "pride"]],
[294, ["Tant de", "so much"]],
[295, ["Sauf", "except"]],
[296, ["Anéantir", "destroy"]],
[297, ["Reprendre", "take more"]],
[298, ["Eteignoir", "snuff"]],
[299, ["Sanglot", "sobbing"]],
[300, ["Interrompre", "interrupt"]],
[301, ["Mensonge", "lie (deceipt)"]],
[302, ["Tousser", "cough"]],
[303, ["Toux", "cough n."]],
[304, ["Tort", "harm"]],
[305, ["Infliger", "inflict"]],
[306, ["Remords", "remorse"]],
[307, ["Douter de", "doubt"]],
[308, ["Malgré", "despite"]],
[309, ["Embaumer", "perfume"]],
[310, ["Réjouir", "delight"]],
[311, ["Juger", "judge"]],
[312, ["S’enfuir", "flee"]],
[313, ["La paire", "pair (of shoes)"]],
[314, ["Plaire", "to please (sth smn)"]],
[315, ["La pointure", "the length and width (size) of a foot"]],
[316, ["Le portefeuille", "purse"]],
[317, ["Tenter", "tempt (smn to choose or try sth)"]],
[318, ["Celui-ci", "this here masculine singular"]],
[319, ["Celui-la", "this there (that)"]],
[320, ["La cabine d’essayage", "trying-on room"]],
[321, ["Une ceinture", "belt"]],
[322, ["Le col", "collar"]],
[323, ["Froisser", "crease"]],
[324, ["Collant", "tights"]],
[325, ["Convenir", "fit"]],
[326, ["Serré", "tight"]],
[327, ["Laine", "woolen"]],
[328, ["La manche", "sleeve"]],
[329, ["Taché", "stained"]],
[330, ["La taille", "size"]],
[331, ["la grandeur", "size"]],
[332, ["La grosseur", "size"]],
[333, ["Habiller", "dress"]],
[334, ["Tenue", "outfit"]],
[335, ["Les escarpins", "high heels"]],
[336, ["Prêter", "lend !"]],
[337, ["L’aise", "pleasure"]],
[338, ["La nourriture", "food"]],
[339, ["Repas", "meal"]],
[340, ["Essuyer", "clean and wipe"]],
[341, ["Balayer", "sweep"]],
[342, ["Appétissant", "appetising"]],
[343, ["La brochette", "scewered (meats)"]],
[344, ["La côtelette", "cutlet"]],
[345, ["la côte", "cutlet"]],
[346, ["La cuisson", "cooking (time)"]],
[347, ["L’épicier", "greengrocer"]],
[348, ["Le mouton", "mutton"]],
[349, ["Le poireau", "spring onion"]],
[350, ["Le rôti", "le morceau - bit (of Beef)"]],
[351, ["Préparer", "prepare"]],
[352, ["père", "father"]],
[353, ["mère", "mother"]],
[354, ["fêter", "celebrate"]],
[355, ["Le légume", "vegetable"]],
[356, ["sûr", "sure"]],
[357, ["rôti", "beef"]],
[358, ["très", "very"]],
[359, ["pâtisserie", "delicatessen"]],
[360, ["à", "to"]],
[361, ["même", "same"]],
[362, ["août", "August"]],
[363, ["Épinards", "spinach"]],
[364, ["Gratin", "french speciality (potatoes au gratin)"]],
[365, ["Mûre (adj)", "ripe (adj)"]],
[366, ["Mûre (noun)", "blackberry (noun)"]],
[367, ["Les étagères", "shelves"]],
[368, ["Surgelé", "frozen"]],
[369, ["Assez de", "enough of"]],
[370, ["Juste assez", "only a bit of"]],
[371, ["Autant…que", "as much as"]],
[372, ["Autant de … que", "as many as"]],
[373, ["L’allée", "aisle"]],
[374, ["Le paquet", "packaging"]],
[375, ["l’emballage", "packaging"]],
[376, ["La coupure", "cut"]],
[377, ["la blessure", "wound"]],
[378, ["Désinfecter (nettoyer)", "disinfect"]],
[379, ["Le pansement", "plaster"]],
[380, ["morceau de tissu", "bit of plaster"]],
[381, ["La plaie", "bandage"]],
[382, ["La Peau", "skin"]],
[383, ["Les points (de suture)", "stitches"]],
[384, ["Saigner", "lose blood - bleeding"]],
[385, ["Alimentaire", "dietary"]],
[386, ["L’Estomac", "stomach"]],
[387, ["Le comprimé", "pill"]],
[388, ["Guérir", "heal"]],
[389, ["L’ordonnance", "prescription and orders"]],
[390, ["Emménager", "move in"]],
[391, ["Pas encore", "yet to"]],
[392, ["Huître", "oyster"]],
[393, ["Oublier de", "Forget"]],
[394, ["aider à", "Help"]],
[395, ["Souffrir", "suffer"]],
[396, ["Douleur", "pain"]],
[397, ["antidouleur", "painkiller"]],
[398, ["Te souvenir", "remember"]],
[399, ["Genou", "knee"]],
[400, ["Dur", "hard"]],
[401, ["Doux", "soft"]],
[402, ["Le guichet", "ticket office"]],
[403, ["La séance", "duration"]],
[404, ["Un réalisateur", "producer"]],
[405, ["Réaliste", "realistic"]],
[406, ["Echouer", "to fail"]],
[407, ["Déconseiller", "not recommend"]],
[408, ["Adhérer", "adhere"]],
[409, ["Grève", "strike"]],
[410, ["Lancée", "momentum"]],
[411, ["Rite", "ritual and rite"]],
[412, ["Gîte", "holiday cottage"]],
[413, ["Cure", "course of treatment"]],
[414, ["Piqûre", "injection"]],
[415, ["Moustique", "mosquito"]],
[416, ["Traiter", "treat (behaviour)"]],
[417, ["Volontiers", "willingly"]],
[418, ["Faire l’affaire", "fit the bill"]],
[419, ["La farine", "flour"]],
[420, ["Veuillez", "Please"]],
[421, ["Goûter", "feed and snack"]],
[422, ["Les Épices", "spice"]],
[423, ["La lessive (savon liquide)", "washing powder / (detergent)"]],
[424, ["Milieu", "middle"]],
[425, ["Pousser", "push"]],
[426, ["Ranger", "put something away"]],
[427, ["Avi", "opinion"]],
[428, ["Suffir", "suffice"]],
[429, ["Falloir", "To have to"]],
[430, ["Retrouver", "meet"]],
[431, ["Salmon", "saumon"]],
[432, ["C’est assez !", "It’s ENOUGH"]],
[433, ["Tellement", "so much"]],
[434, ["Envie", "longing, desire, envy, wish, want"]],
[435, ["Le doigt", "finger"]],
[436, ["Arriver à", "happen to"]],
[437, ["Ramasser", "pick up"]],
[438, ["Un verre", "a glass"]],
[439, ["Pas la peine", "no struggle"]],
[440, ["Aggraver", "aggrevate (wound)"]],
[441, ["Bienveillant", "goodwilling"]],
[442, ["Rétablir Guérir", "rebilitate and heal"]],
[443, ["L’orage", "thunderstorm"]],
[444, ["Le chemin", "the way"]],
[445, ["J’ai besoin de", "I need"]],
[446, ["La serviette hygiénique", "pad"]],
[447, ["Le préservatif", "condom"]],
[448, ["La brosse à dents", "toothbrush"]],
[449, ["Le plat principal", "main course"]],
[450, ["Les noix", "nuts"]],
[451, ["La gare routière", "bus stop"]],
[452, ["La prise", "socket"]],
[453, ["Plus tôt", "earlier"]],
[454, ["A l’heure", "on time"]],
[455, ["En retard", "delayed"]],
[456, ["L’antidouler", "painkiller"]],
[457, ["L’abdomen", "abdomen"]],
[458, ["l’estomac", "stomach"]],
[459, ["La Main", "hand"]],
[460, ["Le bras", "arm"]],
[461, ["Le lieu de naissance", "POB"]],
[462, ["le date de naissance", "DOB"]],
[463, ["Sombre", "dark"]],
[464, ["De toutes les couleurs", "colourful"]],
[465, ["Vide", "empty"]],
[466, ["Il vaut…", "It’s worth…"]],
[467, ["Reconnaissant", "grateful"]],
[468, ["La voisine", "neighbour"]],
[469, ["Un don de sang", "a blood donation"]],
[470, ["Un couteau", "a knife"]],
[471, ["Se couper", "cut oneself"]],
[472, ["Brûlure", "to burn"]],
[473, ["Éternuer", "to sneeze"]],
[474, ["Uu", "mouth closed lips pursed"]],
[475, ["Yy", "lips out smile closed"]],
[476, ["Suivre", "follow"]],
[477, ["J’ai suivi", "I followed"]],
[478, ["Le printemps", "spring"]],
[479, ["Goût", "taste"]],
[480, ["Maladie", "illness (not injury)"]],
[481, ["Soigner", "treat (medical)"]],
[482, ["Rhume", "cold"]],
[483, ["Ça t’aidera", "it will help you"]],
[484, ["Elle attendra d’aller mieux", "She will wait until she is better"]],
[485, ["Étant", "Being"]],
[486, ["ayant", "Having"]],
[487, ["sachant", "Knowing"]],
[488, ["buvant", "Drinking"]],
[489, ["sortant", "Leaving"]],
[490, ["Manquer", "miss and lack"]],
[491, ["Souriant", "smiley"]],
[492, ["Fait", "done"]],
[493, ["Le généraliste", "GP"]],
[494, ["Poursuivre", "pursue"]],
[495, ["continuer", "to continue with something"]],
[496, ["Persévérer", "to persevere"]],
[497, ["Imprimer", "to print"]],
[498, ["L’inconvénient", "inconvenience"]],
[499, ["le désavantage", "inconvenience"]],
[500, ["Par", "by"]],
[501, ["Convaincre", "convince"]],
[502, ["persuader", "persuade someone to do something"]],
[503, ["Envisager", "envisage"]],
[504, ["considérer", "consider"]],
[505, ["Livrer", "deliver"]],
[506, ["La remise", "discount"]],
[507, ["Suggérer", "suggest"]],
[508, ["conseiller", "advise"]],
[509, ["proposer", "suggest"]],
[510, ["L’economie", "saving"]],
[511, ["Réaliser une economie", "achieves"]],
[512, ["Faire des economies", "making cuts and savings"]],
[513, ["Maniére", "way, fashion, manner"]],
[514, ["Renseigner", "inform"]],
[515, ["Exiger", "demand"]],
[516, ["Si je ne me trompe pas", "if I’m not mistaken"]],
[517, ["Davantage", "more or further or for longer"]],
[518, ["Chaque jour davantage", "more each day"]],
[519, ["de plus en plus", "more and more"]],
[520, ["Afficher", "display"]],
[521, ["Eviter", "avoid"]],
[522, ["À la fois (… et)", "at the same time"]],
[523, ["Lors de", "during"]],
[524, ["Donnée", "data"]],
[525, ["Attractif", "qui plait"]],
[526, ["La comparaison (de) (entre)", "The comparison"]],
[527, ["Faire la pointure", "have a size (clothing)"]],
[528, ["Propriétaire", "landlord"]],
[529, ["Le coût", "cost"]],
[530, ["La gamme", "range (of products)"]],
[531, ["Innover", "to innovate"]],
[532, ["La marque", "brand"]],
[533, ["PRÉVOIR", "forecast"]],
[534, ["planifier", "plan"]],
[535, ["imaginer", "imagine"]],
[536, ["anticiper", "anticipate"]],
[537, ["Réduire", "reduce"]],
[538, ["diminuer", "diminish"]],
[539, ["baisser", "lower"]],
[540, ["Frais", "cost and charge"]],
[541, ["Inespéré", "unhoped for"]],
[542, ["imprévu", "unprecedented"]],
[543, ["Se mettre d’accord", "reach an agreement"]],
[544, ["Enseigner l’allemagne", "teach"]],
[545, ["Surmonter", "overcome"]],
[546, ["Apprentissage", "learning"]],
[547, ["Enseigne", "logo and emblem"]],
[548, ["Il se pourrait que", "It may be that"]],
[549, ["L’imprimante", "printer"]],
[550, ["Quoi", "what"]],
[551, ["emboucher", "put sth to your lips"]],
[552, ["sert á faire", "used to do something"]],
[553, ["briller", "to polish (shine)"]],
[554, ["Je pense la meme chose que toi", "I am thinking the same as you"]],
[555, ["J’ai hate de ca", "I can’t wait for that"]],
[556, ["Épine", "thorn"]],
[557, ["Coffre-fort", "safe"]],
[558, ["Se reculer", "step back"]],
[559, ["Ressembler à", "resemble"]],
[560, ["S’effronder", "collapse"]],
[561, ["Lancer un regard (noir)", "glower"]],
[562, ["Espérance", "hope"]],
[563, ["Sourire", "smile"]],
[564, ["Maîtriser", "master"]],
[565, ["Cloche", "bell"]],
[566, ["Prier", "pray"]],
[567, ["Tourner à (qch)", "become"]],
[568, ["Sorte", "sort"]],
[569, ["Craquer", "split"]],
[570, ["Guerre", "war"]],
[571, ["Effort", "effort"]],
[572, ["Lancer", "hurl"]],
[573, ["Pleurer", "cry"]],
[574, ["Coupable", "culprit"]],
[575, ["Dense", "dense"]],
[576, ["Spare (me)", "m’épargner"]],
[577, ["Péril", "peril"]],
[578, ["Dénivelé", "elevation gain"]],
[579, ["Habitude", "Routine"]],
[580, ["Toilette", "Routine"]],
[581, ["Coutume", "Routine"]],
[582, ["Quotidien", "Routine"]],
[583, ["Contribuer à", "contribute to"]],
[584, ["Provenir de ", "originates / comes from"]],
[585, ["reflechir", "reflect"]],
[586, ["Saine", "healthy (feminine)"]],
[587, ["Se préoccuper de", "preoccupied / worried"]],
[588, ["Élever", "raise (holistic)"]],
[589, ["Selon", "according"]],
[590, ["Sondage", "survey"]],
[591, ["Soutenir", "support"]],
[592, ["J’ai couru", "I ran"]],
[593, ["Œil", "eye"]],
[594, ["Ouïr", "hear"]],
[595, ["Trottinette", "scooter"]],
[596, ["Bouilloire", "kettle"]],
[597, ["Passoire", "sieve"]],
[598, ["Egouttoir", "drying up rack"]],
[599, ["CE qui", "sets up what as subject (e.g. what is interesting is the fact)"]],
[600, ["CE que", "sets up what as direct object at beginning of the sentence"]],
[601, ["Une voie", "route, way"]],
[602, ["Peigner", "comb"]],
[603, ["Le congé", "holiday"]],
[604, ["Inégaux", "unequal (plural)"]],
[605, ["Déguster", "manger"]],
[606, ["Gentillesse", "hospitality"]],
[607, ["Grâce au +", "thanks to"]],
[608, ["Principal", "essential, more important"]],
[609, ["Parmi", "among"]],
[610, ["Cependant", "yet"]],
[611, ["Façon", "way"]],
[612, ["Qu’est-ce qui est le mieux ?", "What is the best ?"]],
[613, ["Le harcèlement scolaire", "school bullying"]],
[614, ["Le cyber harcèlement", "cyber bullying"]],
[615, ["Un outil de distraction", "a tool for distraction"]],
[616, ["La sédentarité", "sedentary lifestyle"]],
[617, ["Le règlement intérieur", "school rules and policy"]],
[618, ["Encadrer l’usage", "to supervise the use"]],
[619, ["L’éducation aux medias", "media education"]],
[620, ["Compétence aux medias", "media literacy"]],
[621, ["L’outil pédagogique", "educational tool"]],
[622, ["La sécurité des élèves", "student safety"]],
[623, ["Difficulté d’application", "difficult to implement"]],
[624, ["Gérer", "handle"]],
[625, ["Réseaux sociaux", "social media"]],
[626, ["La baisse", "drop"]],
[627, ["Ayant fini mes devoirs", "Having finished my homework"]],
[628, ["Tout de suite", "immediately"]],
[629, ["À tout de suite", "see you very soon"]],
[630, ["En", "any, one, some, them"]],
[631, ["Y", "it, there"]],
[632, ["Racheter", "buy back"]],
[633, ["Pareil", "the same"]],
[634, ["C’est du pareil au même", "it’s the same difference"]],
[635, ["Les actions", "shares"]],
[636, ["Côté", "side"]],
[637, ["ANTECEDENT + Où", "something where"]],
[638, ["Fort", "strong"]],
[639, ["Aménagé", "done up"]],
[640, ["Très peu", "very little"]],
[641, ["Quoi que", "whatever"]],
[642, ["Quoique", "as much as"]],
[643, ["Apporter", "to bring"]],
[644, ["Emballer", "to pack"]],
[645, ["Toujours", "always, still"]],
[646, ["Cahier", "notebook"]],
[647, ["Trop peu", "too few"]],
[648, ["Auréoler", "endow"]],
[649, ["Boutonnières", "button holes"]],
[650, ["Atteller", "harness"]],
[651, ["Souci", "worry"]],
[652, ["Exercer", "practise"]],
[653, ["Solennellement", "solemnly"]],
[654, ["Concevoir", "design"]],
[655, ["Laïque", "non-religious"]],
[656, ["Croyance", "belief"]],
[657, ["Demeurer", "to remain"]],
[658, ["Je meurs de faim", "I’m starving"]],
[659, ["Verb + le mieux ", "best (adverb)"]],
[660, ["Rejeter", "emit, release, shift"]],
[661, ["Une hausse", "a rise, increase, hike"]],
[662, ["Le milieu", "middle"]],
[663, ["Avi + SUR", "opinion about"]],
[664, ["La ficelle", "string"]],
[665, ["Recoudre", "to stitch"]],
[666, ["L’infirmier", "nurse"]],
[667, ["L’arme", "weapon"]],
[668, ["Tout en", "while"]],
[669, ["Tout de même", "all the same"]],
[670, ["Suit", "follows"]],
[671, ["Laïcité", "secularity"]],
[672, ["Lier", "to tie"]],
[673, ["Élu", "chosen"]],
[674, ["En tant que", "as (something)"]],
[675, ["En tant que tel", "in its current form"]],
[676, ["Saisir", "seize"]],
[677, ["En fait", "actually"]],
[678, ["De plus", "what’s more"]],
[679, ["À tous", "to all"]],
[680, ["Inébranlable", "unwavering"]],
[681, ["Enivré", "inebriated"]],
[682, ["Inaccessible", "inaccessible"]],
[683, ["Studieux", "studious"]],
[684, ["J’en veux un peu plus", "I want a bit more of it"]],
[685, ["Je n’en veux plus", "I don't want any more of that"]],
[686, ["Elle ne mange pas assez de légumes", "She doesn't eat enough vegetables"]],
[687, ["Matières grasses", "fat"]],
[688, ["Je lui conseillerais", "I advised him"]],
[689, ["Digérer le pain", "digest bread"]],
[690, ["Pain de mie", "soft bread"]],
[691, ["Corvée", "chore"]],
[692, ["Bricolage", "DIY"]],
[693, ["Poterie", "pottery"]]]);


let integerArray = []
let VocabLog = new Map()
function getRandomGeorgesFrench() {
  let randomInteger = (Math.floor(Math.random() * GeorgesFrench.size))+1
  document.getElementById("french").value = GeorgesFrench.get(randomInteger)[0];
  document.getElementById("english").value = GeorgesFrench.get(randomInteger)[1];
  let frenchBeen = document.getElementById("french").value
  let englishBeen = document.getElementById("english").value
  VocabLog.set(randomInteger, [frenchBeen+": "+englishBeen])
  integerArray.unshift(randomInteger)
  document.getElementById("previous").value = VocabLog.get(integerArray[1])
}
}



